### ISSUE TITLE
Maps not working on Win10 or OSX

### ISSUE THREAD

**Issue by larspett** [rekonstrukt/swedishbutterflies#13]
Carsten and I are experiencing similar (path-related?) problems with the distribution map generating funktions as we had previously with histograms. We get an interrupt before anything is generated. Am on iPhone now so don’t have system dump available  but everything else down to the distribution maps worked fine

**Comment by mskyttner** [comment]
Is it possible to get a system dump or any log messages from running a fresh session on any of the machines that triggers the issue?

Run this:

```r
library(swedishbutterflies)
library(sp)
library(magick)

occ_sp <- SpatialPoints(coords = sebms_data_sites, 
  proj4string = CRS("+proj=tmerc +lat_0=0 +lon_0=15.80827777777778 +k=1 +x_0=1500000 +y_0=0 +ellps=bessel +units=m +no_defs"))
  
sebms_species_site_plot(occ_sp)$plot %>% image_resize("x500")
`

I can't find any OS-dependent paths from a quick glance.

**Comment by larspett** [comment]
Hej detta behöver jag tyvärr göra från grunden, ser att jag kan ha gjort min fork korrupt och behöver börja om från början för att det ska vara replikerbart. Tyvärr har jag inte rätt på min passphrase för ssh så det funkar inte riktigt. Återkommer så snart som möjligt.

/Lars

**Comment by CarstenKost** [comment]
Here is what happens when I run the code, including session info:

> library(swedishbutterflies)
> library(sp)
> library(magick)
> 
> occ_sp <- SpatialPoints(coords = sebms_data_sites, 
+proj4string = CRS("+proj=tmerc +lat_0=0 +lon_0=15.80827777777778 +k=1 +x_0=1500000 +y_0=0 +ellps=bessel +units=m +no_defs"))
> 
> sebms_species_site_plot(occ_sp)$plot %>% image_resize("x500")
>
>Error in .local(.Object, ...) : 
>
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
>
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Sweden.1252  LC_CTYPE=English_Sweden.1252    LC_MONETARY=English_Sweden.1252
> [4] LC_NUMERIC=C                    LC_TIME=English_Sweden.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] magick_1.9               sp_1.3-1                 swedishbutterflies_0.1.3
> 
> loaded via a namespace (and not attached):
>  [1] zoo_1.8-3           tidyselect_0.2.4    purrr_0.2.5         lattice_0.20-35     ggthemes_4.0.0      colorspace_1.3-2   
>  [7] viridisLite_0.3.0   htmltools_0.3.6     yaml_2.2.0          blob_1.1.1          rlang_0.2.1         hexbin_1.27.2      
> [13] pillar_1.3.0        later_0.7.3         glue_1.3.0          DBI_1.0.0           rappdirs_0.3.1      bit64_0.9-7        
> [19] RColorBrewer_1.1-2  dbplyr_1.2.2        bindrcpp_0.2.2      bindr_0.1.1         plyr_1.8.4          stringr_1.3.1      
> [25] munsell_0.5.0       gtable_0.2.0        raster_2.6-7        htmlwidgets_1.2     latticeExtra_0.6-28 knitr_1.20         
> [31] httpuv_1.4.5        crosstalk_1.0.0     parallel_3.5.1      Rcpp_0.12.18        xtable_1.8-2        scales_0.5.0       
> [37] promises_1.0.1      leaflet_2.0.1       jsonlite_1.5        config_0.3          mime_0.5            bit_1.1-14         
> [43] ggplot2_3.0.0       hms_0.4.2           digest_0.6.15       stringi_1.1.7       rasterVis_0.45      dplyr_0.7.6        
> [49] shiny_1.1.0         grid_3.5.1          cowplot_0.9.3       rgdal_1.3-4         tools_3.5.1         magrittr_1.5       
> [55] lazyeval_0.2.1      tibble_1.4.2        crayon_1.3.4        tidyr_0.8.1         pool_0.1.4.1        pkgconfig_2.0.1    
> [61] lubridate_1.7.4     assertthat_0.2.0    rstudioapi_0.7      RPostgres_1.1.1     R6_2.2.2            compiler_3.5.1

**Comment by mskyttner** [comment]
Thanks for the details. I fired up a VM with Windows and was able to replicate and get the same error message: `Error in .local(.Object, ...)`. 

First looking at the stack trace and then debugging it turned out to be related to this SO post: https://stackoverflow.com/questions/24495487/r-error-thrown-while-using-rgdal-and-raster-packages 

It seems the fix is to embed the data into the package using another filename (without underscore characters). I tried this fix on Windows, rebuilt and installed the package and now get the plot properly when I run this code in a fresh session:

```r

library(swedishbutterflies)
library(sp)

occ_sp <- SpatialPoints(coords = sebms_data_sites, 
  proj4string = CRS("+proj=tmerc +lat_0=0 +lon_0=15.80827777777778 +k=1 +x_0=1500000 +y_0=0 +ellps=bessel +units=m +no_defs"))

library(magick)

sebms_species_site_plot(occ_sp)$plot %>%
  image_resize("700x")
```

**Comment by mskyttner** [comment]
This seems not to be an issue when using Linux as OS. 

Thanks for spotting it!

I plan to update the package to 0.1.4 and include this fix.

**Comment by mskyttner** [comment]
This fix doens't work as intended and needs more work, the TIF file may need to be added as external data...

**Comment by mskyttner** [comment]
The TIF file is now loaded as external data instead (the package has the file bundled as is in `inst/extdata` rather than provided as a package dataset) and this seems to fix this issue when testing in a Windows VM just now.

Could I get a confirmation from @CarstenKost  and/or @larspett that the test code posted earlier in this thread works now with the latest changes?

To check this, reinstall the latest version of the package using `library(devtools); install_github("rekonstrukt/swedishbutterflies")` and then run that test code again.

**Comment by larspett** [comment]
Will check at work tomorrow, left the computer there.

**Comment by larspett** [comment]
It works now but there appears to be a namespace conflict in swedishbutterflies which blocks the loading of magick after swedishbutterflies.

This modified code did the trick, though:

library(magick)
library(swedishbutterflies)
library(sp)

occ_sp <- SpatialPoints(coords = sebms_data_sites,
  proj4string = CRS("+proj=tmerc +lat_0=0 +lon_0=15.80827777777778 +k=1 +x_0=1500000 +y_0=0 +ellps=bessel +units=m +no_defs"))

sebms_species_site_plot(occ_sp)$plot %>%
  image_resize("700x")

/Lars

**Comment by larspett** [comment]
I get this working now but ran into an unexpected result when trying to feed a different site list to the function. I used the attached (more recent) csv file, imported & converted to becomea corresponding tbl as the sebms_data_sites but get a shrunk image (as attached)
![preview](https://user-images.githubusercontent.com/19598308/46804922-240c2700-cd64-11e8-8cd8-5feb9de44cce.png)
[sites.txt](https://github.com/rekonstrukt/swedishbutterflies/files/2468921/sites.txt)

**Comment by larspett** [comment]
Closed, works now
